console.log('This in on Arrays...');

// Array: array is a type of object used to do works like storing anything in it.

    let arr = [2, 45, 67, 89, 78, 12]; // this is how we declare an array...
//array index=  0, 1 , 2,  3,  4,  5
// the array index start from zero
console.log(arr); // to print any array we use this type of request

console.log(arr[4]); // this is how we print any specific element in the array...

let arr1 = [2, 1, 'Asamanta', 'Samanta', true, null, undefined, "IDK"]; // the array can hold any kind of  data type.It may be anything from string to boolean and so on....

// we can replace any element in an array with another element by using this command.....
arr1[7] = 567; // this command will change the value of the seventh element in the array arr1.....

console.log(arr1); // this command can find the length of the array...

console.log(typeof arr1[4]); // to check the tye of data type of any thing in the array, you can use this command.....

console.log(arr1.length); // this command can find the length of the array...

console.log(arr1[0] + arr1[1]); // this is how we can do any type of operation.It is valid only if the selected elements of the array are a number....

console.log(arr[3] + arr1[1]); // this is how we can do any type of operation between elements of different arrays but they have to be a number...

console.log(arr.toString(), typeof arr); // this make an array a string with comma separated values....

console.log(arr1.join(' and ')); 
// this command can join the selected element in the array into one single value by using commas as separators...

let arr2 = [34, 56, 78, 89, 90];
arr2.pop(); // this command will remove the last element of an array....

console.log(arr2); // now if i run this command, it will print all the elements in the array except for the last one as the command has removed the last element from the array...

//Important Function
// we can also add any number of elements to a specific index position in an array by using this command.....
arr2.push('ASamanta' , 56);

console.log(arr2);// when i run this command, it will print all elements as well as 'ASamanta' and 56 with it

arr2.shift(); // this command can remove the first element in an array...
console.log(arr2) // this will print all other elements except for the first one.It works like pop but it removes only first one...

arr2.unshift('Shruti'); // this will add 'Shruti' to the beginning of the array....
console.log(arr2); // this will print all things with 'Shruti' in the beginning

console.log(arr2.length)

delete arr2[1]; // this will delete the second element from an array...
console.log(arr2); // when i run this, it will print everything except for the second one as it has been deleted and show that this will show deleted item printed...
console.log(arr2.length); // but if i search the length of the arr2 Array, it will show that one which was before change

console.log(typeof arr2[1]); // this will show the undefined at the place of the deleted item

let a1 = [1, 2, 3];
let a2 = [3, 4, 5, 6, 7];
let a3 = [8, 9, 10 , 11, 12];

console.log('Array called \'a3\' length is ',a3.length);

console.log(a1.concat(a2, a3)); // this will return a1 array with a2 and a3 with it.It will make a new array but it will not modify the existing arrays

a3.splice(1, 2); // this command can delete any number of elements from a specific index position in an array by using this command but it will not delete the starting position...
console.log(a3 , a3.length); // this will delete two element and give only the undeleted elements